app = "spotify-xvllsw"
primary_region = "iad"

[checks]
  autostart = false
  autoskip = true

[build]

[processes]
  worker = "python main.py"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
