app = "spotify-xvllsw"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["worker"]
  protocol = "tcp"

[[http_service.checks]]
  type = "tcp"
  interval = "100000h"
  timeout = "10s"

[build]

[processes]
  worker = "python main.py"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
