app = 'spotify-xvllsw'
primary_region = 'iad'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  worker = "python main.py"

# Disable all health checks
[checks]
  disabled = true
