# fly.toml app configuration file generated for spotify-xvllsw on 2025-12-03T18:25:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spotify-xvllsw'
primary_region = 'iad'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[processes]
  app = "python main.py"
